"""
Agent 5: Safety Guardrails and Governance Gatekeeper Agent
Responsibilities:
- Comprehensive supervisor reviewing all prior agent outputs
- Enforces Gate 5: Clinical Governance and Emergency Triage Gate
- Triggers acute red-flag alerts for severe hyperglycemia (Glucose >= 250 mg/dL)
- Enforces official bilingual medical disclaimers
- Generates final audit trail certifying clinical clearance
"""

from typing import List, Dict, Any, Optional
from datetime import datetime
from schemas import (
    PatientInput, TriageResult, PredictionResult,
    ClinicalReasoningResult, LifestylePlanResult, GatekeeperAuditResult
)

class SafetyGatekeeperAgent:
    def __init__(self):
        self.agent_name = "Safety Guardrails & Governance Gatekeeper Agent"
        self.agent_name_ar = "وكيل الحوكمة وبوابات الأمان وضبط الجودة"

    def execute(
        self,
        patient: PatientInput,
        triage: TriageResult,
        prediction: PredictionResult,
        reasoning: ClinicalReasoningResult,
        lifestyle: LifestylePlanResult
    ) -> GatekeeperAuditResult:
        audit_trail = []
        is_approved = True
        emergency_alert = False
        emergency_msg_ar = None
        emergency_msg_en = None

        # 1. Audit Prior Gates
        if triage.gate_status == "PASSED":
            audit_trail.append("Gate 1 (Biological Plausibility): VERIFIED")
        else:
            audit_trail.append(f"Gate 1: FAILED ({triage.gate_status})")
            is_approved = False

        if prediction.gate_status == "PASSED":
            audit_trail.append("Gate 2 (Statistical Calibration): VERIFIED")
        else:
            audit_trail.append(f"Gate 2: FAILED ({prediction.gate_status})")
            is_approved = False

        if reasoning.gate_status == "PASSED":
            audit_trail.append("Gate 3 (Semantic Alignment): VERIFIED")
        else:
            audit_trail.append(f"Gate 3: FAILED ({reasoning.gate_status})")
            is_approved = False

        if lifestyle.gate_status == "PASSED":
            audit_trail.append("Gate 4 (Lifestyle Feasibility): VERIFIED")
        else:
            audit_trail.append(f"Gate 4: FAILED ({lifestyle.gate_status})")
            is_approved = False

        # 2. Critical Emergency Check (Severe Hyperglycemia / DKA Risk)
        glucose = triage.sanitized_features.get('glucose', patient.glucose)
        if glucose >= 250.0:
            emergency_alert = True
            emergency_msg_ar = (
                "⚠️ تحذير سريري عاجل: مستوى سكر الدم الحالي يتجاوز 250 mg/dL! "
                "يشير هذا الارتفاع الحرج إلى احتمالية الإصابة بمضاعفات حادة مثل الحماض الكيتوني السكري (DKA) "
                "أو متلازمة فرط الأسمولية. يجب التوجه الفوري إلى أقرب مركز طوارئ أو مراجعة الطبيب المعالج فوراً!"
            )
            emergency_msg_en = (
                "⚠️ CRITICAL CLINICAL ALERT: Blood glucose exceeds 250 mg/dL! "
                "This severe hyperglycemia level presents imminent risk of Diabetic Ketoacidosis (DKA) "
                "or Hyperosmolar Hyperglycemic State (HHS). Immediate emergency hospital evaluation is required!"
            )
            audit_trail.append("Gate 5 (Emergency Triage): CRITICAL ALERT TRIGGERED")
        else:
            audit_trail.append("Gate 5 (Emergency Triage): STABLE CLINICAL PROFILE")

        # 3. Bilingual Medical Disclaimers
        disclaimer_ar = (
            "إخلاء مسؤولية سريري وقانوني: هذا التقرير صادر عن نظام ذكاء اصطناعي متعدد الوكلاء كأداة دعم قرار سريري استرشادية، "
            "ولا يعد بديلاً عن الفحص الطبي المباشر أو التحاليل المخبرية المعتمدة (مثل HbA1c أو اختبار تحمل الجلوكوز OGTT). "
            "يرجى استشارة الطبيب المختص قبل اتخاذ أي قرارات علاجية أو دوائية."
        )
        disclaimer_en = (
            "Clinical & Legal Disclaimer: This report is generated by an Agentic Clinical Decision Support System "
            "intended strictly for educational and screening guidance. It does not constitute a definitive medical diagnosis "
            "nor replace in-person consultation with a licensed physician and laboratory confirmation (HbA1c/OGTT)."
        )

        return GatekeeperAuditResult(
            is_approved=is_approved,
            emergency_alert_triggered=emergency_alert,
            emergency_message_ar=emergency_msg_ar,
            emergency_message_en=emergency_msg_en,
            safety_disclaimer_ar=disclaimer_ar,
            safety_disclaimer_en=disclaimer_en,
            audit_trail=audit_trail,
            gate_status="PASSED" if is_approved else "REJECTED_AUDIT_FAILURE"
        )
